Nodes:
- Height: 760
  Width: 1241
  X: 0
  Y: 0
  Template: Boundary
  Id: MyApp
- Height: 80
  Id: ChangeView
  Width: 120
  X: 200
  Y: 200
  Template: UseCase
- Height: 80
  Id: Zoom
  Width: 120
  X: 200
  Y: 600
  Template: UseCase
- Height: 64
  Id: Architect
  Width: 64
  X: 10
  Y: 300
  Template: Actor
Edges:
- Ending: None
  From: Architect
  FromLabel: ''
  LabelOffsetPerCent: 0
  Style: None
  Text: ''
  To: ChangeView
  ToLabel: ''
- Ending: ClosedArrow
  From: Zoom
  FromLabel: ''
  LabelOffsetPerCent: 0
  Style: None
  Text: ''
  To: ChangeView
  ToLabel: ''
